### ISSUE TITLE
ExceLint

### ISSUE THREAD

**Issue by jmsilva** [ExceLint/ExceLint#2]
ExceLint not available for Excel Mac users

**Comment by dbarowy** [comment]
Hi @jmsilva,

Have a look at https://github.com/plasma-umass/Excelint-addin.  New development is happening over there for Office 365.  Sadly, Office for the Mac does not have the same developer hooks we need to run ExceLint, so it is not possible to port over to the Mac.  But Office 365 does, and I believe that you can run that one on the Mac.  @emeryberger can probably better answer this question.

**Comment by emeryberger** [comment]
Yes, ExceLint-addin works great on the Mac -- that's what I use as my development and testing platform! (@dbarowy we should put a note in the README.md to point people there)

**Comment by emeryberger** [comment]
Updated README.md.
